#!/usr/bin/env php
<?php

/*
 * OpenSID Artisan Console Runner
 * Kabupaten Banggai Kepulauan Multi-Tenant SaaS
 */

define('ARTISAN_CLI', true);

// Sisipkan 'artisan' ke argumen CLI agar router CodeIgniter mencocokkan route 'artisan/{any1?}...'
$args   = $_SERVER['argv'] ?? ['artisan'];
$script = array_shift($args);

$_SERVER['argv'] = array_merge([$script, 'artisan'], $args);
$_SERVER['argc'] = count($_SERVER['argv']);

require_once __DIR__ . '/index.php';
