#!/usr/bin/env php
<?php

/*
 * OpenSID Artisan Console Runner
 * Kabupaten Banggai Kepulauan Multi-Tenant SaaS
 */

define('ARTISAN_CLI', true);

// Set routing ke controller Artisan
$_SERVER['PATH_INFO']   = '/artisan';
$_SERVER['REQUEST_URI'] = '/artisan';

require_once __DIR__ . '/index.php';
